services:
  app:
    build: ./server/
    command: [ "sh", "-c", "npm run build && npm run start" ]
    ports:
      - "8080:8080"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./server
          target: /app
          ignore:
            - build/**
