services:
  app:
    build: ./server/
    command: [ "sh", "-c", "npm run build && npm run start" ]
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    develop:
      watch:
        - action: rebuild
          path: ./server
          target: /app
          ignore:
            - build/**

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    container_name: my-mysql
    env_file:
      - .env
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  db-data:
